---
- name: Install nginx
  apt: name=nginx
- name: Load SSL certificate
  synchronize: src="{{ ssl_certificate_pem }}" dest="/etc/nginx/{{ server_hostname }}.pem"
- name: Load SSL certificate key
  synchronize: src="{{ ssl_certificate_key_pem }}" dest="/etc/nginx/{{ server_hostname }}_key.pem"
- name: Copy nginx configs
  template: src=wordpress.conf dest="/etc/nginx/sites-available/{{ server_hostname }}"
- name: Enable site
  file: src="/etc/nginx/sites-available/{{ server_hostname }}" state=link path="/etc/nginx/sites-enabled/{{ server_hostname }}"
  notify: reload nginx
- name: Disable default configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx
