---
- name: Install nginx
  apt: name=nginx
- name: Copy nginx configs
  template: src=wordpress.conf dest=/etc/nginx/sites-available/wordpress
- name: Enable site
  file: src=/etc/nginx/sites-available/wordpress  state=link path=/etc/nginx/sites-enabled/wordpress
  notify: reload nginx
- name: Disable default configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx
