---
- name: Install php-fpm
  apt: name={{ item }}
  with_items:
    - php7.0-fpm
    - php7.0-gd
    - php7.0-mysql
    - php7.0-curl
    - php7.0-xml
- name: Set up /var/run/php-fpm
  file: state=directory path=/var/run/php-fpm owner=www-data group=www-data
- name: Copy configuration from template for php-fpm
  template: src=wordpress.conf dest="/etc/php/7.0/fpm/pool.d/{{ server_hostname }}.conf"
  notify: restart php-fpm
- name: Remove default pool
  file: path=/etc/php/7.0/fpm/pool.d/www.conf state=absent
  notify: restart php-fpm
